parameters:
  DATABASE_URL: ${DATABASE_URL}
  GENAI_AGENT_URL: ${GENAI_AGENT_URL}
  GENAI_API_KEY: ${GENAI_API_KEY}
  BLUE_HOST: ${BLUE_HOST}
  GREEN_HOST: ${GREEN_HOST}
  ALERTS_REPO: ${ALERTS_REPO}
  GH_TOKEN: ${GH_TOKEN}

packages:
  - name: monitoring
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GENAI_AGENT_URL: ${GENAI_AGENT_URL}
      GENAI_API_KEY: ${GENAI_API_KEY}
      BLUE_HOST: ${BLUE_HOST}
      GREEN_HOST: ${GREEN_HOST}
      GH_TOKEN: ${GH_TOKEN}
      ALERTS_REPO: ${ALERTS_REPO}
    functions:
      - name: scheduler
        runtime: nodejs:18
        main: main
        limits:
          timeout: 60000
          memory: 128
        triggers:
          - name: scheduler-trigger
            sourceType: scheduler
            sourceDetails:
              cron: "* * * * *"

      - name: collect-logs
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 60000
          memory: 128

      - name: analyze-logs
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 120000
          memory: 256

      - name: detect-issues
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 60000
          memory: 128

      - name: predict-issues
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 120000
          memory: 256

      - name: send-digest
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 60000
          memory: 128

      - name: cleanup-data
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 120000
          memory: 256

      - name: fleexstack-sample-app-version-bump-bot
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 60000
          memory: 128

      - name: ai-agent-get-runbook
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 30000
          memory: 128

      - name: ai-agent-search-incidents
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 30000
          memory: 128

      - name: ai-agent-search-github-issues
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 30000
          memory: 128

      - name: sync-docs-to-spaces
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 120000
          memory: 256
        environment:
          GH_TOKEN: ${GH_TOKEN}
          DOCS_REPO: MikeBild/fleexstack
          DOCS_PATH: docs
          SPACES_BUCKET: fleexstack-monitoring
          SPACES_REGION: fra1
          SPACES_ACCESS_KEY_ID: ${SPACES_ACCESS_KEY_ID}
          SPACES_SECRET_ACCESS_KEY: ${SPACES_SECRET_ACCESS_KEY}

      - name: analyze-e2e-results
        runtime: nodejs:18
        main: main
        web: true
        limits:
          timeout: 120000
          memory: 256
