parameters:
  DATABASE_URL: ${DATABASE_URL}
  GENAI_AGENT_URL: ${GENAI_AGENT_URL}
  BLUE_HOST: ${BLUE_HOST}
  GREEN_HOST: ${GREEN_HOST}
  ALERTS_REPO: ${ALERTS_REPO}
  GH_TOKEN: ${GH_TOKEN}

packages:
  - name: monitoring
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GENAI_AGENT_URL: ${GENAI_AGENT_URL}
      BLUE_HOST: ${BLUE_HOST}
      GREEN_HOST: ${GREEN_HOST}
    functions:
      - name: scheduler
        runtime: nodejs:18
        main: index.js
        limits:
          timeout: 60000
          memory: 128
        triggers:
          - name: scheduler-trigger
            sourceType: scheduler
            sourceDetails:
              cron: "* * * * *"

      - name: collect-logs
        runtime: nodejs:18
        main: index.js
        limits:
          timeout: 60000
          memory: 128

      - name: analyze-logs
        runtime: nodejs:18
        main: index.js
        limits:
          timeout: 120000
          memory: 256

      - name: detect-issues
        runtime: nodejs:18
        main: index.js
        limits:
          timeout: 60000
          memory: 128

      - name: predict-issues
        runtime: nodejs:18
        main: index.js
        limits:
          timeout: 120000
          memory: 256

      - name: send-digest
        runtime: nodejs:18
        main: index.js
        limits:
          timeout: 60000
          memory: 128

      - name: cleanup-data
        runtime: nodejs:18
        main: index.js
        limits:
          timeout: 120000
          memory: 256
